version: '3'
services:
  billing:
    build: 
      context: ./billing-service
      dockerfile: Dockerfile
    container_name: billing
    ports:
     - "5009:3009"
    restart: always

  inventory:
    build: 
      context: ./inventory-service
      dockerfile: Dockerfile
    container_name: inventory
    ports:
     - "5002:3002"
    restart: always

  shipping:
    build: 
      context: ./shipping-service
      dockerfile: Dockerfile
    container_name: shipping
    ports:
     - "5001:3001"
    restart: always

  users:
    build: 
      context: ./users-service
      dockerfile: Dockerfile
    container_name: users
    ports:
     - "5007:3007"
    restart: always